# Generated by Django 4.2.10 on 2024-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapists',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
