# Generated by Django 4.2.10 on 2024-03-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapists',
            old_name='image',
            new_name='profile_image',
        ),
    ]
