# Generated by Django 4.2.10 on 2024-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_therapists_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapists',
            options={'ordering': ['first_name']},
        ),
        migrations.RemoveField(
            model_name='therapists',
            name='name',
        ),
        migrations.AddField(
            model_name='therapists',
            name='first_name',
            field=models.CharField(default='first name', max_length=255),
        ),
        migrations.AddField(
            model_name='therapists',
            name='last_name',
            field=models.CharField(default='last name', max_length=255),
        ),
    ]
