# Generated by Django 4.2.10 on 2024-02-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_therapists_name_alter_therapists_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapists',
            options={'ordering': ['name']},
        ),
    ]
