# Generated by Django 4.2.10 on 2024-03-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_alter_therapists_options_remove_therapists_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='therapists',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
