# Generated by Django 4.2.10 on 2024-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_alter_therapists_bio_alter_therapists_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='profile_image',
            field=models.ImageField(default='profile', upload_to='./static/images/t_images/'),
        ),
    ]
