# Generated by Django 4.2.11 on 2024-03-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_appointmentmanager_therapist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmanager',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
