# Generated by Django 4.2.11 on 2024-03-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_alter_appointmentmanager_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmanager',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
