# Generated by Django 4.2.11 on 2024-03-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0005_alter_appointmentmanager_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmanager',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
