# Generated by Django 4.2.10 on 2024-03-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0005_alter_therapists_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapists',
            old_name='user',
            new_name='username',
        ),
    ]
