# Generated by Django 4.2.10 on 2024-03-06 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('therapist', '0006_rename_user_therapists_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapists',
            name='username',
        ),
        migrations.AddField(
            model_name='therapists',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapists', to=settings.AUTH_USER_MODEL),
        ),
    ]
