# Generated by Django 4.2.11 on 2024-03-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0006_appointmentmanager_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmanager',
            name='time',
            field=models.CharField(choices=[('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM')], max_length=5),
        ),
    ]
