# Generated by Django 4.2.10 on 2024-03-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0007_remove_therapists_username_therapists_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapists',
            name='user',
        ),
    ]
