# Generated by Django 4.2.11 on 2024-03-13 09:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0007_alter_therapists_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
