# Generated by Django 4.2.10 on 2024-03-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0008_remove_therapists_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='static/images/therapist_profile_pics'),
        ),
    ]
