# Generated by Django 4.2.10 on 2024-03-06 12:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0009_alter_therapists_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
