# Generated by Django 4.2.11 on 2024-03-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_profile_completed_info'),
        ('therapist', '0010_alter_appointmentmanager_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmanager',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_appointment', to='profile.profile'),
        ),
    ]
