# Generated by Django 4.2.11 on 2024-03-25 08:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0012_alter_appointmentmanager_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
