# Generated by Django 4.2.11 on 2024-09-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0014_therapists_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentmanager',
            unique_together={('therapist', 'date', 'time')},
        ),
    ]
