# Generated by Django 4.2.11 on 2024-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('consultation_type', models.IntegerField(choices=[[0, 'Info'], [1, 'Complaint'], [2, 'Make a Suggestion'], [3, 'Happy about the services']])),
                ('message', models.TextField()),
            ],
        ),
    ]
