# Generated by Django 4.2.11 on 2024-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='consultation_type',
            field=models.IntegerField(blank=True, choices=[[0, 'Info'], [1, 'Complaint'], [2, 'Make a Suggestion'], [3, 'Happy about the services']]),
        ),
    ]
